import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getFirestore, doc, setDoc, getDoc, updateDoc, onSnapshot } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyD0Q0N2i4WRjJuRl1sa9gUJXvT0jy52Pzs",authDomain:"game-robney.firebaseapp.com",projectId:"game-robney",storageBucket:"game-robney.firebasestorage.app",messagingSenderId:"776079948578",appId:"1:776079948578:web:664781fb3c6d7db71cc37b"};
const app=initializeApp(firebaseConfig); const db=getFirestore(app);
const lobby=document.getElementById("lobby"),gameScreen=document.getElementById("gameScreen"),status=document.getElementById("status"),canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d");
let myName="",roomCode="",myPlayer=1,roomData=null,gameStarted=false,gameOver=false,animationStarted=false,timerLoop=null,combatLoop=null,lastActions={p1:0,p2:0};
let shake=0,localFx="",localFxUntil=0;
const ATTACKS={
 light:{damage:9,range:115,windup:90,recovery:170,beats:"grab",gain:12},
 heavy:{damage:20,range:125,windup:220,recovery:330,beats:"light",gain:18},
 grab:{damage:15,range:90,windup:120,recovery:300,beats:"block",gain:16},
 overdrive:{damage:38,range:145,windup:180,recovery:520,beats:"light,heavy,grab,block",gain:-100},
 fatality:{damage:100,range:105,windup:120,recovery:900,beats:"block",gain:-100}
};
const now=()=>Date.now();
function resizeCanvas(){const r=canvas.getBoundingClientRect();canvas.width=r.width*devicePixelRatio;canvas.height=r.height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
addEventListener("resize",resizeCanvas);
addEventListener("DOMContentLoaded",()=>{const n=localStorage.getItem("robneyFightLastName"),r=localStorage.getItem("robneyFightLastRoom");if(n)document.getElementById("playerName").value=n;if(r)document.getElementById("roomCode").value=r});

document.getElementById("createRoom").onclick=async()=>{const name=document.getElementById("playerName").value.trim();if(!name){status.textContent="Enter your fighter name.";return}myName=name;roomCode=Math.random().toString(36).substring(2,8).toUpperCase();myPlayer=1;try{await setDoc(doc(db,"rooms",roomCode),{host:name,players:[name],p1:baseP(80),p2:baseP(Math.max(220,innerWidth-140)),status:"waiting",timer:75,winner:null,createdAt:now()});openGame()}catch(e){status.textContent=e.message}};

document.getElementById("joinRoom").onclick=async()=>{const name=document.getElementById("playerName").value.trim(),code=document.getElementById("roomCode").value.trim().toUpperCase();if(!name||!code){status.textContent="Enter name and room code.";return}try{const ref=doc(db,"rooms",code),snap=await getDoc(ref);if(!snap.exists()){status.textContent="Room not found.";return}const data=snap.data(),players=data.players||[],existing=players.findIndex(x=>x===name);if(existing===0||existing===1){myName=name;roomCode=code;myPlayer=existing+1;await updateDoc(ref,{status:players.length>=2?"ready":"waiting",["p"+myPlayer+".action"]:"idle"});openGame();return}if(players.length>=2){status.textContent="Room is full. Use the name you used before to reconnect.";return}players.push(name);myName=name;roomCode=code;myPlayer=2;await updateDoc(ref,{players,status:"ready","p2.x":Math.max(220,innerWidth-140),"p2.y":0,"p2.action":"idle"});openGame()}catch(e){status.textContent=e.message}};

function baseP(x){return{x,y:0,health:100,momentum:0,action:"idle",actionAt:0,lockedUntil:0,invulnUntil:0,hitstunUntil:0}}
function openGame(){localStorage.setItem("robneyFightLastRoom",roomCode);localStorage.setItem("robneyFightLastName",myName);localStorage.setItem("robneyFightLastPlayer",String(myPlayer));lobby.classList.add("hidden");gameScreen.classList.remove("hidden");document.getElementById("liveRoomCode").textContent=roomCode;resizeCanvas();startListener();if(!animationStarted){animationStarted=true;requestAnimationFrame(gameLoop)}}

document.getElementById("copyRoom").onclick=async()=>{try{await navigator.clipboard.writeText(roomCode);const b=document.getElementById("copyRoom");b.textContent="COPIED!";setTimeout(()=>b.textContent="COPY",1200)}catch{showMessage(roomCode)}};
function startListener(){onSnapshot(doc(db,"rooms",roomCode),snap=>{if(!snap.exists())return;roomData=snap.data();updateUI();if(roomData.status==="ready"&&(roomData.players||[]).length===2){gameStarted=true;if(myPlayer===1)startHostLoops()}if(roomData.winner!==null&&roomData.winner!==undefined)finishGame(roomData.winner)})}
function startHostLoops(){if(!timerLoop)timerLoop=setInterval(hostTick,1000);if(!combatLoop)combatLoop=setInterval(hostCombat,50)}
async function hostTick(){if(myPlayer!==1||!roomData||!gameStarted||gameOver)return;const t=Math.max(0,(roomData.timer??75)-1);if(t<=0){const h1=roomData.p1.health,h2=roomData.p2.health;await updateDoc(doc(db,"rooms",roomCode),{timer:0,winner:h1===h2?"draw":h1>h2?1:2})}else await updateDoc(doc(db,"rooms",roomCode),{timer:t})}

function updateUI(){if(!roomData)return;const p1=roomData.p1||{},p2=roomData.p2||{},players=roomData.players||[];document.getElementById("p1Name").textContent=players[0]||"PLAYER 1";document.getElementById("p2Name").textContent=players[1]||"PLAYER 2";document.getElementById("p1Health").style.width=Math.max(0,p1.health??100)+"%";document.getElementById("p2Health").style.width=Math.max(0,p2.health??100)+"%";document.getElementById("p1Momentum").style.width=Math.max(0,p1.momentum??0)+"%";document.getElementById("p2Momentum").style.width=Math.max(0,p2.momentum??0)+"%";document.getElementById("timer").textContent=roomData.timer??75;const enemy=myPlayer===1?p2:p1;const f=document.getElementById("fatality");if(f)f.classList.toggle("ready",enemy.health<=20&&distance(myPlayer===1?p1:p2,enemy)<=120)}
function distance(a,b){return Math.abs((a?.x??0)-(b?.x??0))}

async function move(dx){if(!roomData||gameOver||!gameStarted)return;const key="p"+myPlayer,me=roomData[key],t=now();if((me.lockedUntil||0)>t)return;const maxX=Math.max(20,canvas.clientWidth-65),next=Math.max(20,Math.min(maxX,(me.x??80)+dx));await updateDoc(doc(db,"rooms",roomCode),{[key+".x"]:next,[key+".action"]:"idle",[key+".actionAt"]:0})}
async function jump(){if(!roomData||gameOver||!gameStarted)return;const key="p"+myPlayer,me=roomData[key],t=now();if((me.lockedUntil||0)>t)return;await updateDoc(doc(db,"rooms",roomCode),{[key+".y"]:-70,[key+".lockedUntil"]:t+320});setTimeout(()=>updateDoc(doc(db,"rooms",roomCode),{[key+".y"]:0,[key+".lockedUntil"]:0}).catch(()=>{}),320)}
async function chooseMove(move){if(!roomData||gameOver||!gameStarted)return;const key="p"+myPlayer,me=roomData[key],t=now();if((me.lockedUntil||0)>t)return;if(move==="overdrive"&&(me.momentum??0)<100){showMessage("NEED 100 MOMENTUM");return}if(move==="fatality"){const enemy=roomData[myPlayer===1?"p2":"p1"];if((enemy.health??100)>20||distance(me,enemy)>120){showMessage("GET CLOSE • ENEMY ≤20 HP");return}}const def=ATTACKS[move];if(!def)return;await updateDoc(doc(db,"rooms",roomCode),{[key+".action"]:move,[key+".actionAt"]:t,[key+".lockedUntil"]:t+def.recovery})}

let moveHold=null;
function bindHold(id,fn){const el=document.getElementById(id);if(!el)return;el.addEventListener("pointerdown",e=>{e.preventDefault();fn();if(id==="left"||id==="right"){clearInterval(moveHold);moveHold=setInterval(fn,90)}});["pointerup","pointercancel","pointerleave"].forEach(ev=>el.addEventListener(ev,()=>{if(id==="left"||id==="right"){clearInterval(moveHold);moveHold=null}}))}
bindHold("left",()=>move(-35)); bindHold("right",()=>move(35));
document.getElementById("jump")?.addEventListener("pointerdown",e=>{e.preventDefault();jump()});
for(const [id,fn] of [["light",()=>chooseMove("light")],["heavy",()=>chooseMove("heavy")],["grab",()=>chooseMove("grab")],["dash",()=>chooseMove("dash")],["overdrive",()=>chooseMove("overdrive")],["fatality",()=>chooseMove("fatality")]])document.getElementById(id)?.addEventListener("pointerdown",e=>{e.preventDefault();fn()});

async function hostCombat(){if(myPlayer!==1||!roomData||!gameStarted||gameOver)return;const t=now();const p1={...roomData.p1},p2={...roomData.p2};let changed=false;for(const attackerKey of ["p1","p2"]){const defenderKey=attackerKey==="p1"?"p2":"p1";const a={...roomData[attackerKey]},d={...roomData[defenderKey]};const action=a.action,at=a.actionAt||0;if(!action||action==="idle"||at<=lastActions[attackerKey])continue;lastActions[attackerKey]=at;const def=ATTACKS[action];if(action==="block"||action==="dash"){changed=true;continue}if(!def)continue;if(distance(a,d)>def.range)continue;if((d.invulnUntil||0)>t){continue}const targetAction=d.action||"idle";let hit=false,damage=def.damage;const beats=def.beats.split(",");if(targetAction==="dash"){continue}if(targetAction==="block"){hit=action==="grab"||action==="fatality"?true:false;if(!hit)damage=0}else if(beats.includes(targetAction)){hit=true;damage=def.damage}else if(targetAction==="idle"){hit=true;damage=def.damage}else{hit=true;damage=def.damage}
if(action==="fatality" && d.health>20)hit=false;
if(hit&&damage>0){d.health=Math.max(0,d.health-damage);d.momentum=Math.max(0,Math.min(100,(d.momentum||0)+15));a.momentum=action==="overdrive"||action==="fatality"?0:Math.min(100,(a.momentum||0)+def.gain);d.hitstunUntil=t+Math.min(420,def.recovery+100);a.action="idle";d.action="idle";changed=true;localFx=(action==="fatality"?"☠ FATALITY ☠":action.toUpperCase()+" HIT");localFxUntil=t+550;shake=14;}
else if(!hit&&targetAction==="block"){a.action="idle";changed=true;}
else if(action==="heavy"||action==="grab"||action==="light"||action==="overdrive"||action==="fatality"){a.action="idle";changed=true}
roomData[attackerKey]=a;roomData[defenderKey]=d;
}
if(changed){const updates={"p1.health":p1.health,"p2.health":p2.health,"p1.momentum":p1.momentum,"p2.momentum":p2.momentum,"p1.action":p1.action,"p2.action":p2.action,"p1.hitstunUntil":p1.hitstunUntil||0,"p2.hitstunUntil":p2.hitstunUntil||0};if(p1.health<=0||p2.health<=0)updates.winner=p1.health<=0&&p2.health<=0?"draw":p1.health<=0?2:1;await updateDoc(doc(db,"rooms",roomCode),updates)}}

async function chooseBlock(active){const key="p"+myPlayer;if(!roomData||gameOver||!gameStarted)return;const t=now();if(active)await updateDoc(doc(db,"rooms",roomCode),{[key+".action"]:"block",[key+".actionAt"]:t,[key+".lockedUntil"]:t+180});else await updateDoc(doc(db,"rooms",roomCode),{[key+".action"]:"idle",[key+".actionAt"]:0,[key+".lockedUntil"]:0})}
const blockBtn=document.getElementById("block");blockBtn.addEventListener("pointerdown",e=>{e.preventDefault();chooseBlock(true)});blockBtn.addEventListener("pointerup",()=>chooseBlock(false));blockBtn.addEventListener("pointercancel",()=>chooseBlock(false));

function gameLoop(){drawGame();requestAnimationFrame(gameLoop)}
function drawGame(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);if(!roomData)return;let sx=0,sy=0;if(shake>0){sx=(Math.random()-.5)*shake;sy=(Math.random()-.5)*shake;shake--}ctx.save();ctx.translate(sx,sy);const ground=h-70;ctx.fillStyle="#202938";ctx.fillRect(0,ground,w,70);ctx.fillStyle="#475569";ctx.fillRect(0,ground,w,4);drawFighter(roomData.p1,"#2563eb",ground);drawFighter(roomData.p2,"#ef2222",ground);ctx.restore();if(localFxUntil>now()){ctx.save();ctx.font="bold 24px sans-serif";ctx.textAlign="center";ctx.fillStyle="#fff";ctx.fillText(localFx,w/2,80);ctx.restore()}}
function drawFighter(f,color,ground){if(!f)return;const x=f.x??0,base=ground+(f.y??0);ctx.save();if((f.momentum??0)>=100){ctx.shadowBlur=24;ctx.shadowColor="#facc15"}ctx.fillStyle=color;ctx.fillRect(x+12,base-50,12,50);ctx.fillRect(x+34,base-50,12,50);ctx.fillRect(x+5,base-120,48,70);ctx.beginPath();ctx.arc(x+29,base-140,20,0,Math.PI*2);ctx.fill();const a=f.action;if(a==="light"){ctx.fillStyle="#bfdbfe";ctx.fillRect(x+48,base-105,65,10)}if(a==="heavy"){ctx.fillStyle="#fecaca";ctx.fillRect(x+45,base-100,85,16)}if(a==="grab"){ctx.strokeStyle="#ddd6fe";ctx.lineWidth=7;ctx.beginPath();ctx.arc(x+60,base-98,34,-1,1);ctx.stroke()}if(a==="block"){ctx.strokeStyle="#e5e7eb";ctx.lineWidth=7;ctx.beginPath();ctx.arc(x+29,base-104,42,-1.5,1.5);ctx.stroke()}if(a==="dash"){ctx.globalAlpha=.35;ctx.fillStyle=color;ctx.fillRect(x-28,base-120,38,70)}if(a==="overdrive"){ctx.strokeStyle="#fde047";ctx.lineWidth=8;ctx.beginPath();ctx.arc(x+29,base-100,70,0,Math.PI*2);ctx.stroke()}if(a==="fatality"){ctx.strokeStyle="#ef4444";ctx.lineWidth=10;ctx.beginPath();ctx.arc(x+29,base-105,76,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function showMessage(text){const m=document.getElementById("message");m.textContent=text;setTimeout(()=>{if(m.textContent===text)m.textContent=""},650)}
function finishGame(winner){if(gameOver)return;gameOver=true;showMessage(winner==="draw"?"DRAW!":(winner===1?roomData.players[0]:roomData.players[1])+" WINS!");setTimeout(()=>showMessage("☠ FATALITY ☠"),850);setTimeout(restartRound,3000)}
async function restartRound(){if(myPlayer!==1)return;await updateDoc(doc(db,"rooms",roomCode),{"p1":baseP(80),"p2":baseP(Math.max(220,canvas.clientWidth-100)),timer:75,winner:null,status:"ready"});gameOver=false;lastActions={p1:0,p2:0}}

addEventListener("keydown",e=>{if(e.repeat)return;if(e.key==="ArrowLeft")move(-35);if(e.key==="ArrowRight")move(35);if(e.key==="a")chooseMove("light");if(e.key==="s")chooseMove("heavy");if(e.key==="d")chooseMove("grab");if(e.key==="f")chooseBlock(true);if(e.key==="g")chooseMove("dash");if(e.key==="h")chooseMove("overdrive");if(e.key==="j")chooseMove("fatality")});
